import React from 'react';
import './TermsOfServicePage.css';

const TermsOfServicePage: React.FC = () => {
  return (
    <div className="terms-page">
      <div className="terms-container">
        <header className="terms-header">
          <h1 className="terms-title">Terms of Service</h1>
          <p className="terms-subtitle">
            Last updated: January 1, 2025
          </p>
        </header>

        <div className="terms-content">
          <section className="terms-section">
            <h2>Acceptance of Terms</h2>
            <p>
              By accessing and using Play Any Card Game ("the Service"), you accept and agree to 
              be bound by the terms and provision of this agreement. If you do not agree to abide 
              by these terms, please do not use this service.
            </p>
          </section>

          <section className="terms-section">
            <h2>Description of Service</h2>
            <p>
              Play Any Card Game is an AI-powered platform that allows users to create custom 
              card games by describing their ideas in natural language. Our AI system generates 
              playable card games based on user input.
            </p>
          </section>

          <section className="terms-section">
            <h2>User Responsibilities</h2>
            <h3>Acceptable Use</h3>
            <p>You agree to use the Service only for lawful purposes. You must not:</p>
            <ul>
              <li>Create content that is offensive, harmful, or inappropriate</li>
              <li>Attempt to reverse engineer or exploit the AI system</li>
              <li>Use the Service to create games that infringe on others' intellectual property</li>
              <li>Engage in any activity that disrupts or interferes with the Service</li>
              <li>Share or distribute harmful or malicious content</li>
            </ul>

            <h3>Content Creation</h3>
            <p>
              When creating games, you are responsible for ensuring that your game descriptions 
              and concepts do not violate any laws, regulations, or third-party rights.
            </p>
          </section>

          <section className="terms-section">
            <h2>Intellectual Property</h2>
            <h3>Service Ownership</h3>
            <p>
              The Play Any Card Game platform, including its AI technology, design, and code, 
              is owned by us and protected by intellectual property laws.
            </p>

            <h3>User-Generated Content</h3>
            <p>
              You retain ownership of the game concepts you create. However, by using our Service, 
              you grant us a non-exclusive license to process your input through our AI system 
              and generate games based on your descriptions.
            </p>

            <h3>Generated Games</h3>
            <p>
              Games generated by our AI system are provided for your personal use. You may not 
              claim exclusive ownership over basic game mechanics or concepts that may be common 
              or similar to existing games.
            </p>
          </section>

          <section className="terms-section">
            <h2>AI-Generated Content</h2>
            <p>
              Our Service uses artificial intelligence to generate card games. Please note:
            </p>
            <ul>
              <li>AI-generated games may occasionally contain errors or imbalances</li>
              <li>Generated content is based on your input and AI interpretation</li>
              <li>We do not guarantee the uniqueness or originality of generated games</li>
              <li>You should review and test generated games before extensive use</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>Privacy and Data</h2>
            <p>
              Your privacy is important to us. Our collection and use of personal information 
              is governed by our Privacy Policy, which is incorporated into these Terms by reference.
            </p>
          </section>

          <section className="terms-section">
            <h2>Service Availability</h2>
            <p>
              We strive to provide continuous access to our Service, but we cannot guarantee 
              100% uptime. The Service may be temporarily unavailable due to:
            </p>
            <ul>
              <li>Maintenance and updates</li>
              <li>Technical difficulties</li>
              <li>Third-party service interruptions</li>
              <li>Force majeure events</li>
            </ul>
          </section>

          <section className="terms-section">
            <h2>Disclaimers and Limitations</h2>
            <h3>Service Disclaimer</h3>
            <p>
              The Service is provided "as is" without any warranties, express or implied. 
              We disclaim all warranties, including but not limited to merchantability, 
              fitness for a particular purpose, and non-infringement.
            </p>

            <h3>Limitation of Liability</h3>
            <p>
              In no event shall we be liable for any indirect, incidental, special, or 
              consequential damages arising out of or in connection with your use of the Service.
            </p>
          </section>

          <section className="terms-section">
            <h2>Account Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any 
              time, with or without notice, for conduct that we believe violates these Terms 
              or is harmful to other users or our business interests.
            </p>
          </section>

          <section className="terms-section">
            <h2>Third-Party Services</h2>
            <p>
              Our Service may integrate with third-party services (such as AI providers). 
              Your use of such services is subject to their respective terms of service. 
              We are not responsible for third-party services or content.
            </p>
          </section>

          <section className="terms-section">
            <h2>Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws 
              applicable in our jurisdiction. Any disputes arising from these Terms or the 
              Service shall be resolved through appropriate legal channels.
            </p>
          </section>

          <section className="terms-section">
            <h2>Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users 
              of significant changes by updating the "Last updated" date. Your continued use 
              of the Service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section className="terms-section">
            <h2>Contact Information</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <div className="contact-info">
              <p>Email: mirotammi44@gmail.com</p>
              <p>Website: <a href="https://mteif.com" target="_blank" rel="noopener noreferrer">mteif.com</a></p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
